name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Run Flake Check
        run: nix flake check --all-systems

  # build-systems:
  #   needs: [flake-check]
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - host: s01
  #           runner: ubuntu-latest
  #
  #   runs-on: ${{ matrix.runner }}
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: DeterminateSystems/nix-installer-action@v11
  #     - name: Enable Magic Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@v7
  #     - name: Build system for ${{ matrix.host }}
  #       run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

